config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get "dashboard", to: "dashboard#index"

  resources :boards do
    resources :lists
    resources :board_users
  end

  resources :lists do
    resources :items
  end

  resources :items do
    resources :item_members
  end

  namespace :api do
    resources :boards do
      resources :lists, only: [:index], controller: "lists"
      resources :list_positions, only: [:index, :update], controller: "list_positions"
    end

    put "item_positions", to: "item_positions#update" 

    resources :items, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true

  has_many :lists, dependent: :destroy

  has_many :board_users, dependent: :destroy
  has_many :members, through: :board_users, source: :user

  after_create :assign_user_as_member
  def assign_user_as_member
    members << user
  end
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  has_many :item_members, dependent: :destroy
  has_many :members, through: :item_members, source: :user
end

app/models/item_member.rb
class ItemMember < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  validates :title, presence: true

  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/api/item_positions_controller.rb
class Api::ItemPositionsController < ApplicationController
  protect_from_forgery with: :null_session

  def update
    
    items = items_params[:items].map do |item_data|
      item = Item.find(item_data[:id])
      item.position = item_data[:position]
      item.list_id = item_data[:list_id]
      item
    end

    Item.import items, on_duplicate_key_update: [:position, :list_id]

    render json: items
  end

  private

  def items_params
    params
  end
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController
  protect_from_forgery with: :null_session

  def show
    item = Item.find(params[:id])

    render json: ItemRepresenter.new(item).as_json
  end
  
end

app/controllers/api/list_positions_controller.rb
class Api::ListPositionsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def update
    lists = board.lists.order(position: :asc).to_a
    delete_index = lists.index { |list| list.id == params[:id].to_i }
    list = lists.delete_at(delete_index)
    lists.insert(params[:position].to_i, list)
    lists.each_with_index do |list, index|
      list.position = index
    end

    List.import lists, on_duplicate_key_update: [:position]

    render json: ListsRepresenter.new(lists).as_json
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    lists = board.lists.order(position: :asc)
    
    render json: ListsRepresenter.new(lists).as_json
  end
  
  private

  def board
    @board ||= Board.find(params[:board_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @board_user = board.board_users.new
  end

  def create
    board_user_ids = board.members.ids
    
    user_ids_to_destroy = board_user_ids - user_ids
    
    BoardUser.where(board: board, user_id: user_ids_to_destroy).delete_all
    users_to_assign = User.where(id: user_ids).where.not(id: board.reload.members.ids)
    board.members << users_to_assign
    redirect_to board_path(board)
  end

  private

  def user_ids 
    params[:user_ids].map(&:to_i).reject(&:zero?)
  end

  def board
    @board ||= Board.find(params[:board_id]) # luc vao edit se dc goi va gan cho @board nay, (caching)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def show
    authorize board
    
  end

  def new
    @board = Board.new
  end

  def edit
    authorize board
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    authorize board

    if board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize board
    board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id]) # luc vao edit se dc goi va gan cho @board nay, (caching)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Board.order(:created_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?    
  end
end

app/controllers/item_members_controller.rb
class ItemMembersController < ApplicationController
  before_action :authenticate_user!

  def new
    item
  end

  def create
    item_user_ids = item.members.ids
    
    user_ids_to_destroy = item_user_ids - user_ids
    
    ItemMember.where(item: item, user_id: user_ids_to_destroy).delete_all
    users_to_assign = User.where(id: user_ids).where.not(id: item.reload.members.ids)
    item.members << users_to_assign
    redirect_to board_path(item.list.board)
  end

  private

  def user_ids 
    params[:user_ids].map(&:to_i).reject(&:zero?)
  end

  def item
    @item ||= Item.find(params[:item_id]) # luc vao edit se dc goi va gan cho @board nay, (caching)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def new
    @item = list.items.new
  end

  def edit
    @item = list.items.find(params[:id])
  end

  def create
    @item = list.items.new(item_params)

    if @item.save
      redirect_to board_path(list.board)
    else
      render :new
    end
  end

  def update
    @item = list.items.find(params[:id])
    
    if @item.update(item_params)
      redirect_to board_path(list.board)
    else 
      render :edit
    end
  end

  def destroy
    @item = list.items.find(params[:id])
    @item.destroy

    head :no_content
  end

  private

  def list
    @list ||= List.find(params[:list_id])
  end

  def item_params
    params.require(:item).permit(:title, :description)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def new
    @list = board.lists.new
  end

  def edit
    @list = board.lists.find(params[:id])
  end

  def create
    @list = board.lists.new(list_params)

    if @list.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def update
    @list = board.lists.find(params[:id])
    
    if @list.update(list_params)
      redirect_to board_path(board)
    else 
      render :edit
    end
  end

  def destroy
    @list = board.lists.find(params[:id])
    @list.destroy

    head :no_content
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/api/boards_helper.rb
module Api::BoardsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/board_users/new.html.erb
<%= form_with url: board_board_users_path(@board), local: true do |f| %>
  <div class="bg-indigo-50 min-h-screen md:px-20 pt-6">
    <div class=" bg-white rounded-md px-6 py-10 max-w-2xl mx-auto">
      <h1 class="text-center text-2xl font-bold mb-10">Board Member List</h1>

      <div class="space-y-4">
        <fieldset class="mb-5">
          <legend class="text-lg font-bold mb-3">Members</legend>

          <% User.find_each do |user| %>
            <div class="flex justify-between mb-4">
              <%= f.label :user_ids, class: "text-sm text-gray-900" do %>
                <%= user.email %>
              <% end %>
              <%= f.check_box :user_ids, { class: "bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-4 w-4 rounded", multiple: true, checked: @board.members.include?(user), disabled: @board.user == user }, user.id %>
            </div>
          <% end %> 
        
        </fieldset>

          <div class="flex items-center justify-end gap-5">
            <%= link_to "Cancel", board_path(@board), class: "custom-link" %>
            <%= f.submit "Assign Members", class: "bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 cursor-pointer" %>
          </div>
      </div>
    </div>
  </div>
<% end %>
  

app/views/boards/_form.html.erb
<%= form_with model: board, local: true do |f| %>
  <div class="bg-indigo-50 min-h-screen md:px-20 pt-6">
    <div class=" bg-white rounded-md px-6 py-10 max-w-2xl mx-auto">
      <% if board.new_record? %>
        <h1 class="text-center text-2xl font-bold mb-10">New Board</h1>
      <% else %>
        <h1 class="text-center text-2xl font-bold mb-10">Edit Board</h1>
      <% end %>

      <div class="space-y-4">
          <div class="field">
            <%= f.label :name, class: "block mt-3 font-semibold" %>
            <%= f.text_field :name, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          </div>

          <div class="flex items-center justify-end gap-4">
            <%= link_to "Cancel", root_path, class: "custom-link" %>
            <%= f.submit class: "bg-purple-500 text-white py-2 px-6 rounded-md hover:bg-purple-600 cursor-pointer" %>
          </div>
      </div>
    </div>
  </div>
<% end %>
  

app/views/boards/edit.html.erb
<%= render "form", board: @board %>

app/views/boards/new.html.erb
<%= form_with model: @board, local: true do |f| %>
  <div class="bg-indigo-50 min-h-screen md:px-20 pt-6">
    <div class=" bg-white rounded-md px-6 py-10 max-w-2xl mx-auto">
      <h1 class="text-center text-2xl font-bold mb-10">New Board</h1>
      <div class="space-y-4">
          <div class="field">
            <%= f.label :name, class: "block mt-3 font-semibold" %>
            <%= f.text_field :name, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          </div>

          <div class="flex items-center justify-end gap-4">
            <%= link_to "Cancel", root_path, class: "custom-link" %>
            <%= f.submit "Create", class: "bg-purple-500 text-white py-2 px-6 rounded-md hover:bg-purple-600 cursor-pointer" %>
          </div>
      </div>
    </div>
  </div>
<% end %>
  

app/views/boards/show.html.erb
<div class="container mx-auto p-6">
  <div class="mb-5">
    <%= link_to "+ Add New Member", new_board_board_user_path(@board), class: "bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 cursor-pointer" %>
  </div>

  <div 
    data-controller="board" 
    id="board" class="overflow-x-scroll" 
    data-api-url="<%= api_board_lists_path(@board) %>" 
    data-list-positions-api-url="<%= api_board_list_positions_path(@board) %>" 
    data-board-lists-url="<%= board_lists_path(@board) %>"
    data-item-positions-api-url="<%= api_item_positions_path %>"
  >
  </div>
</div>

<%= render "shared/modal" %>

app/views/home/index.html.erb
<p>Hello World from HomeController</p>

app/views/item_members/new.html.erb
<%= form_with url: item_item_members_path(@item), local: true do |f| %>
  <div class="bg-indigo-50 min-h-screen md:px-20 pt-6">
    <div class=" bg-white rounded-md px-6 py-10 max-w-2xl mx-auto">
      <h1 class="text-center text-2xl font-bold mb-10">Item Member List</h1>

      <div class="space-y-4">
        <fieldset class="mb-5">
          <legend class="text-lg font-bold mb-3">Members</legend>

          <% @item.list.board.members.find_each do |user| %>
            <div class="flex justify-between mb-4">
              <%= f.label :user_ids, class: "text-sm text-gray-900" do %>
                <%= user.email %>
              <% end %>
              <%= f.check_box :user_ids, { class: "bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-4 w-4 rounded", multiple: true, checked: @item.members.include?(user) }, user.id %>
            </div>
          <% end %> 
        
        </fieldset>

          <div class="flex items-center justify-end gap-5">
            <%= link_to "Cancel", board_path(@item.list.board), class: "custom-link" %>
            <%= f.submit "Assign Members", class: "bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 cursor-pointer" %>
          </div>
      </div>
    </div>
  </div>
<% end %>
  

app/views/items/_form.html.erb
<%= form_with model: [list, item], local: true do |f| %>
  <div class="bg-indigo-50 min-h-screen md:px-20 pt-6">
    <div class=" bg-white rounded-md px-6 py-10 max-w-2xl mx-auto">
      <% if item.new_record? %>
        <h1 class="text-center text-2xl font-bold mb-10">New Item</h1>
      <% else %>
        <h1 class="text-center text-2xl font-bold mb-10">Edit Item <%= item.title %></h1>
      <% end %>

      <div class="space-y-4">
          <div class="field">
            <%= f.label :title, class: "block mt-3 font-semibold" %>
            <%= f.text_field :title, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          </div>

          <div class="field">
            <%= f.label :description, class: "block mt-3 font-semibold" %>
            <%= f.text_area :description, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          </div>

          <div class="flex items-center justify-end gap-5">
            <%= link_to "Cancel", root_path, class: "custom-link" %>
            <%= f.submit class: "bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 cursor-pointer" %>
          </div>
      </div>
    </div>
  </div>
<% end %>
  

app/views/items/edit.html.erb
<%= render "form", list: @list, item: @item %>

app/views/items/new.html.erb
<%= form_with model: [@list, @item], local: true do |f| %>
  <div class="bg-indigo-50 min-h-screen md:px-20 pt-6">
    <div class=" bg-white rounded-md px-6 py-10 max-w-2xl mx-auto">
      <% if @item.new_record? %>
        <h1 class="text-center text-2xl font-bold mb-10">New Item</h1>
      <% else %>
        <h1 class="text-center text-2xl font-bold mb-10">Edit Item <%= item.title %></h1>
      <% end %>

      <div class="space-y-4">
          <div class="field">
            <%= f.label :title, class: "block mt-3 font-semibold" %>
            <%= f.text_field :title, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          </div>

          <div class="field">
            <%= f.label :description, class: "block mt-3 font-semibold" %>
            <%= f.text_area :description, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          </div>

          <div class="flex items-center justify-end gap-5">
            <%= link_to "Cancel", root_path, class: "custom-link" %>
            <%= f.submit class: "bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 cursor-pointer" %>
          </div>
      </div>
    </div>
  </div>
<% end %>
  

app/views/lists/_form.html.erb
<%= form_with model: [board, list], local: true do |f| %>
  <div class="bg-indigo-50 min-h-screen md:px-20 pt-6">
    <div class=" bg-white rounded-md px-6 py-10 max-w-2xl mx-auto">
      <% if list.new_record? %>
        <h1 class="text-center text-2xl font-bold mb-10">New List</h1>
      <% else %>
        <h1 class="text-center text-2xl font-bold mb-10">Edit List <%= list.title %></h1>
      <% end %>

      <div class="space-y-4">
          <div class="field">
            <%= f.label :title, class: "block mt-3 font-semibold" %>
            <%= f.text_field :title, class: "border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-indigo-500 focus:ring-1 rounded-md" %>
          </div>

          <div class="flex items-center justify-end gap-5">
            <%= link_to "Cancel", root_path, class: "custom-link" %>
            <%= f.submit class: "bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 cursor-pointer" %>
          </div>
      </div>
    </div>
  </div>
<% end %>
  

app/views/lists/edit.html.erb
<%= render "form", board: @board, list: @list %>

app/views/lists/new.html.erb
<%= render "form", board: @board, list: @list %>