config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get "dashboard", to: "dashboard#index"

  resources :boards do
    resources :lists
    resources :board_users
  end

  resources :lists do
    resources :items
  end

  resources :items do
    resources :item_members
  end

  namespace :api do
    resources :boards do
      resources :lists, only: [:index], controller: "lists"
      resources :list_positions, only: [:index, :update], controller: "list_positions"
    end

    put "item_positions", to: "item_positions#update" 

    resources :items, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true

  has_many :lists, dependent: :destroy

  has_many :board_users, dependent: :destroy
  has_many :members, through: :board_users, source: :user

  after_create :assign_user_as_member
  def assign_user_as_member
    members << user
  end
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  has_many :item_members, dependent: :destroy
  has_many :members, through: :item_members, source: :user
end

app/models/item_member.rb
class ItemMember < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  validates :title, presence: true

  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController
  protect_from_forgery with: :null_session

  def show
    item = Item.find(params[:id])

    render json: ItemRepresenter.new(item).as_json
  end
  
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    lists = board.lists.order(position: :asc)
    
    render json: ListsRepresenter.new(lists).as_json
  end
  
  private

  def board
    @board ||= Board.find(params[:board_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @board_user = board.board_users.new
  end

  def create
    board_user_ids = board.members.ids
    
    user_ids_to_destroy = board_user_ids - user_ids
    
    BoardUser.where(board: board, user_id: user_ids_to_destroy).delete_all
    users_to_assign = User.where(id: user_ids).where.not(id: board.reload.members.ids)
    board.members << users_to_assign
    redirect_to board_path(board)
  end

  private

  def user_ids 
    params[:user_ids].map(&:to_i).reject(&:zero?)
  end

  def board
    @board ||= Board.find(params[:board_id]) # luc vao edit se dc goi va gan cho @board nay, (caching)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def show
    authorize board
    
  end

  def new
    @board = Board.new
  end

  def edit
    authorize board
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    authorize board

    if board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize board
    board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id]) # luc vao edit se dc goi va gan cho @board nay, (caching)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Board.order(:created_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?    
  end
end

app/controllers/item_members_controller.rb
class ItemMembersController < ApplicationController
  before_action :authenticate_user!

  def new
    item
  end

  def create
    item_user_ids = item.members.ids
    
    user_ids_to_destroy = item_user_ids - user_ids
    
    ItemMember.where(item: item, user_id: user_ids_to_destroy).delete_all
    users_to_assign = User.where(id: user_ids).where.not(id: item.reload.members.ids)
    item.members << users_to_assign
    redirect_to board_path(item.list.board)
  end

  private

  def user_ids 
    params[:user_ids].map(&:to_i).reject(&:zero?)
  end

  def item
    @item ||= Item.find(params[:item_id]) # luc vao edit se dc goi va gan cho @board nay, (caching)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def new
    @item = list.items.new
  end

  def edit
    @item = list.items.find(params[:id])
  end

  def create
    @item = list.items.new(item_params)

    if @item.save
      redirect_to board_path(list.board)
    else
      render :new
    end
  end

  def update
    @item = list.items.find(params[:id])
    
    if @item.update(item_params)
      redirect_to board_path(list.board)
    else 
      render :edit
    end
  end

  def destroy
    @item = list.items.find(params[:id])
    @item.destroy

    head :no_content
  end

  private

  def list
    @list ||= List.find(params[:list_id])
  end

  def item_params
    params.require(:item).permit(:title, :description)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def new
    @list = board.lists.new
  end

  def edit
    @list = board.lists.find(params[:id])
  end

  def create
    @list = board.lists.new(list_params)

    if @list.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def update
    @list = board.lists.find(params[:id])
    
    if @list.update(list_params)
      redirect_to board_path(board)
    else 
      render :edit
    end
  end

  def destroy
    @list = board.lists.find(params[:id])
    @list.destroy

    head :no_content
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/api/boards_helper.rb
module Api::BoardsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_header.html.erb
<div class="border-b bg-white">
  <div class="h-16 mx-auto px-5 flex items-center justify-between">
      <%= link_to "Trello", root_path, class: "text-2xl cursor-pointer custom-link" %>
      
      <ul class="flex items-center gap-5">
        <% if user_signed_in? %>
          <% if controller_name == "boards" && action_name == "show" %>
            <%= link_to "New List", new_board_list_path(@board), class: "custom-link" %>
          <% else %>
            <%= link_to "New Board", new_board_path, class: "custom-link" %>
          <% end %>

          <%= link_to "Dashboard", root_path, class: "custom-link" %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "custom-link" %>
        <% else %>
          <%= link_to "Register", new_user_registration_path, class: "custom-link" %>
          <%= link_to "Login", new_user_session_path, class: "custom-link" %>
        <% end %>
      </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_modal.html.erb
<div data-controller="modal" id="modal-wrapper" class="hidden">
  <div class="bg-slate-800 bg-opacity-50 flex justify-center items-center absolute top-0 right-0 bottom-0 left-0">
    <div id="modal-panel" class="bg-white min-w-[300px] p-5 rounded-md flex flex-col gap-3">
      <button data-modal-target="cancelButton" class="font-bold text-xl w-fit">&#x2715</button>
      <h2 id="item-title" class="font-bold text-xl"></h2>
      <p id="item-description"></p>
      <div class="flex justify-between items-center gap-5">
        <%= link_to "Edit", nil, id: "item-edit-link", class: "font-medium text-center text-blue-700 hover:text-blue-500" %>
        <%= link_to "Delete", nil, id: "item-delete-link", class: "font-medium text-center text-red-700 hover:text-red-500" %>
      </div>      
      <%= link_to "Assign Members to Item", nil, id: "item-assign-member-link", class: "w-fit bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 cursor-pointer" %>

      <div>
        <h2 class="text-lg font-bold mb-3">Members Assigned</h2>
        <ul id="item-members-list"></ul>
      </div>
    </div>
  </div>
<div>